stages:
    - test
    - build
    - deploy


build_job:
    image: docker:26.1.1
    stage: test
    services:
        - docker:26.1.1-dind
    variables:
        DOCKER_TLS_CERDIR: "/certs"
    before_script:
        - echo $CI_REGISTRY_PASSWORD | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    script:
        - docker build -t accwilson23055/pythontest .
        - docker tag accwilson23055/pythontest:latest accwilson23055/pythontest:tagname
        - docker push accwilson23055/pythontest:tagname
        - docker logout

run_tests:
    image: python:latest
    stage: build
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - python -m pytest
