stages:
    - test
    - build
    - deploy

run_tests:
    stage: test
    image: python:latest
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - python -m pytest

build_job:
    image: docker:26.1.1
    services:
        - docker:26.1.1-dind
    variables:
        DOCKER_TLS_CERDIR: "/certs"
    stage: build
    before_script:
        - echo "$CI_REGISTRY_PASSWORD" | docker login $CI_REGISTRY --username $CI_REGISTRY_USER --password-stdin
    script:
        - docker build -t accwilson23055/pythontest:dockersoftforpython .
        - docker push accwilson23055/pythontest:dockersoftforpython
        - docker logout