stages:
    - test
    - build
    - deploy

run_tests:
    image: python:latest
    stage: test
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - python -m pytest


build_job:
    image: docker:26.1.1
    stage: build
    services:
        - docker:26.1.1-dind
    variables:
        DOCKER_TLS_CERDIR: "/certs"
    before_script:
        - docker login --username=accwilson23055 --password=7865505R@za
        - unset PASSWORD
    script:
        - docker build -t accwilson23055/pythontest .
        - docker tag accwilson23055/pythontest accwilson23055/pythontestlab:forlab
        - docker push accwilson23055/pythontestlab:forlab
        - docker logout


