stages:
    - test
    - build
    - deploy


build_job:
    image: docker:26.1.1
    stage: test
    services:
        - docker:26.1.1-dind
    variables:
        DOCKER_TLS_CERDIR: "/certs"
    before_script:
        - echo -n "$pass_github" | docker login --username "$user_github" --password-stdin
        - unset PASSWORD
    script:
        - docker build -t accwilson23055/pythontest .
        - docker tag accwilson23055/pythontest accwilson23055/pythontestlab:forlab
        - docker push accwilson23055/pythontestlab:forlab
        - docker logout

run_tests:
    image: python:latest
    stage: build
    before_script:
        - pip install --upgrade pip
        - pip install -r requirements.txt
    script:
        - python -m pytest
